---
- name: "update apt packages."
  apt:
    update_cache: yes

- name: "upgrade packages"
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: "Install Npm and NodeJS"
  apt:
    name: ["nodejs", "npm"]
    state: present

- name: "Install PM2"
  npm:
    name: pm2
    global: yes

- name: "Create a directory"
  file:
    path: ~/web
    state: directory

- name: "Copy index.js"
  copy:
    src: index.js
    dest: ~/web/index.js

- name: Start web server
  command: pm2 start ~/web/index.js -f
